capstone-project 73rd FIFA pull request
theresetuyi/theresetuyi-Capstone-project73rdFIFA- pull request #1
Opened 2023-02-15 08:36 UTC by theresetuyi

## capstone project - Conference page

Apply best practices in HTML code.
Use the CSS 
Use JavaScript events.
Use objects to store and access data.
Communicate technical concepts to other technical people.

2023-02-15 21:28 UTC, cynthiainga requested changes
Hi @theresetuyi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct Github flow ✔️ 
- [ ] Descriptive PR ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Please kindly use descriptive commit messages - each commit should be small enough to describe it in one sentence. The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). Please don't forget this for your next commit messages 🙃 


> |     | Some examples of descriptive commits: | Some commits that are not descriptive:|     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="943" alt="Screen Shot 2023-02-16 at 00 25 53" src="https://user-images.githubusercontent.com/74501523/219171344-d1f3dee1-2567-412a-a32a-5b6e567a85f5.png"> | <img width="787" alt="Screen Shot 2023-02-16 at 00 26 17" src="https://user-images.githubusercontent.com/74501523/219171514-65a698b1-d508-4c10-b437-81c6886a9fa4.png"> |

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 21:28 UTC, cynthiainga commented on README.md
> +
- [ ] Good job so far but you still need to add your links to your live demo and presentation demo 🙃 
- [ ] For the live demo you should deploy your project using the Github page and add the link to your README file also make sure the project is deployed properly, and all pages, links, and images work as expected 😉 😉
- [ ] Also you should record a video presenting the features of the project that follow the instructions below 👇👇:
  - The maximum length of the video is 5 minutes,
  - The video contains a clear and objective description about the project,
  - The video contains a demo of the project, showing the pages in different screen sizes.,
  - The video contains a highlight about a piece of the code that you find interesting or are proud of making.

2023-02-15 21:28 UTC, cynthiainga commented on README.md
> +- Big thanks to the [Microverse](https://bit.ly/MicroverseTN) community with a special mention of my coding partners, morning session teams, standup teams and reviewers.
- [ ] The README should contain an "Acknowledgements" section that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/), please kindly add it 🙃 🙃

2023-02-15 21:28 UTC, cynthiainga commented on README.md
> +This project is [MIT](./LICENSE.txt) licensed.
- [ ] The link that you provided here is broken it is direct to `page not found`, please kindly fix that also update your MIT license file 🙃 😉

2023-02-15 21:28 UTC, cynthiainga commented on README.md
> +
- [ ] Please kindly add your contact info here like your `Github, Twitter, LinkedIn,...` 😁

2023-02-15 21:28 UTC, cynthiainga commented on README.md
> +Feel free to check the [issues page](h
- [OPTIONAL] I think it can be better if you add the link that can direct users to the issue page directly if they need to suggest you something to improve or add to your project,... 😉

2023-02-15 21:28 UTC, cynthiainga commented on about.html
> +            </div>
- [ ] I think this part should be in the `header` tag because is a part of the header and you should put it into the `nav` tag cause is the navigation part in the header and for HTML best practice 🙃 😉
- [ ] Also do this change in your index.html file 👌👌

2023-02-15 21:28 UTC, cynthiainga commented on about.html
> +        </div>
- [ ] Both pages should contain the same navbar and footer, but your about page misses the logo you should fix your path link of the logo 🙃 
- [ ] I think also it can be better if you increase a little bit the font-size of your nav-link and move it a bit to the right side 😁 

Your design

About page

<img width="938" alt="Screen Shot 2023-02-15 at 22 31 08" src="https://user-images.githubusercontent.com/74501523/219136516-f5f1b523-7ccd-45a1-b2ea-b9b59bb316f3.png">

Home page

<img width="938" alt="Screen Shot 2023-02-15 at 22 30 59" src="https://user-images.githubusercontent.com/74501523/219136593-b5b4f564-8b20-4899-95b5-902aa4dc8923.png">

2023-02-15 21:28 UTC, cynthiainga commented on about.html
> +    </div>
- [ ] The footer should have a logo aligned to the left and text aligned to the right, but you have only the text kindly add the logo as well for all the pages `About and Home` 🙃 
- [ ] The footer for mobile has a white background color for all the pages, but for you, in the mobile version, the about page's footer has a dark background please kindly fix that 😉 

<img width="322" alt="Screen Shot 2023-02-15 at 23 05 17" src="https://user-images.githubusercontent.com/74501523/219141011-60a8a56a-a535-43fa-9507-3342f82af55e.png">

- [ ] The background should cover the footer, also make sure your text is visible. Normally when we have a dark background the text is supposed to be in white color to be more visible 😁 😁 

<img width="874" alt="Screen Shot 2023-02-15 at 23 00 33" src="https://user-images.githubusercontent.com/74501523/219141075-7ae4e24c-9c92-4053-ba14-6bdfe2791f90.png">

2023-02-15 21:28 UTC, cynthiainga commented on index.html
> +            </section>
- [ ] Good job so far, but you still have some issues that need to be fixed 🙃.  You are supposed to follow the provided design guidelines for this project but you must just personalize the content 😁
  - Please kindly change the background image of the title, in the original design they use the below one 👇 

![font](https://user-images.githubusercontent.com/74501523/219146114-6079d65e-7190-488a-a99b-f65973de17f2.jpeg)

  - I think also it would be better if you decrease a little bit your title size by 3.8vw or 4vw instead of 5vw 🙃 

> |     | Your design                     | Original design                     |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="1021" alt="Screen Shot 2023-02-15 at 23 10 55" src="https://user-images.githubusercontent.com/74501523/219147634-3c28ef20-af0e-42b6-8742-2f33c978a713.png"> | <img width="983" alt="Screen Shot 2023-02-15 at 23 16 20" src="https://user-images.githubusercontent.com/74501523/219147742-8557f373-a6f5-45a7-abca-24e55ebed936.png"> |

2023-02-15 21:28 UTC, cynthiainga commented on index.html
> +            <h3>Main Program</h3>
- [ ] You miss a divider under your title, please kindly add it 🙃 


> |     | Your design                     | Original design                     |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="641" alt="Screen Shot 2023-02-15 at 23 41 12" src="https://user-images.githubusercontent.com/74501523/219151673-8e916827-a593-40c8-a6b9-ec2a090c285d.png"> | <img width="641" alt="Screen Shot 2023-02-15 at 23 41 38" src="https://user-images.githubusercontent.com/74501523/219151894-0e24f768-c799-4648-a2be-668620fb9ddf.png"> |

2023-02-15 21:28 UTC, cynthiainga commented on js/contect.js
> +  ];
- [ ] This section contains six individual articles, but you have only 4 kindly add the two other articles 🙃 😉

2023-02-15 21:28 UTC, cynthiainga commented on about.html
> +            </section>
- [ ] This section contains a top section with a central column that includes a page title, a text block with the page description, and a line with contact information or any other prompt under it, but you don't have the line with contact information kindly add it 🙃 🙃 
- [ ] Please kindly decrease a little bit the size of your title and your paragraph as well, they are too big 🙃 🙃. Also, center your paragraph 👍
- [ ] Kindly use the same color as in the original design for the title 🙃 

> |     | Your design                     | Original design                     |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="1003" alt="Screen Shot 2023-02-15 at 23 52 43" src="https://user-images.githubusercontent.com/74501523/219159262-7ff86f4a-26d9-439b-b7a8-2dcd6521c7e0.png"> | <img width="879" alt="Screen Shot 2023-02-15 at 23 58 14" src="https://user-images.githubusercontent.com/74501523/219159514-d8c98e02-644a-4e3a-8b50-3121902194ea.png"> |

2023-02-15 21:28 UTC, cynthiainga commented on about.html
> +
- [ ] You literally miss one section in your website, this section contains a middle section with a centered column that includes a section header, a divider, a paragraph of text, and an image or large logo 🙃. Please kindly add it 😁 😁 

Original design

<img width="873" alt="Screen Shot 2023-02-16 at 00 06 34" src="https://user-images.githubusercontent.com/74501523/219161672-c0c45317-64eb-4d4f-9e77-83370718ba22.png">

2023-02-15 21:28 UTC, cynthiainga commented on about.html
> +    </section>
- [ ] This section contains a centered column that includes a section header, a divider, a line of text, and two images with text centered over them, please kindly fix this section.
- [ ] In mobile this section images are organized in a vertical column and in desktop images are organized in a horizontal row 🙃 🙃 

> |     | Your design                     | Original design                     |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="854" alt="Screen Shot 2023-02-16 at 00 12 39" src="https://user-images.githubusercontent.com/74501523/219165481-d1a520db-dc24-4f66-8ea9-cd485e0c2f33.png"> | <img width="873" alt="Screen Shot 2023-02-16 at 00 12 09" src="https://user-images.githubusercontent.com/74501523/219165672-3af8a4ee-ead0-4bfb-a0d0-abe1ea1f49b6.png"> |

2023-02-15 21:28 UTC, cynthiainga commented on about.html
> +                <a class="nav-link" href="about.html">about</a>
- [ ] Please kindly capitalized this link, it should be `About` instead of `about` 😉 😉 . Do the change even in index.html file 🙃

2023-02-17 14:42 UTC, BertrandConxy requested changes
Hi @theresetuyi, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- No linter errors
- good improvement based on the previous reviewer's suggestions


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 14:42 UTC, BertrandConxy commented on README.md
> +[Project Link]https://github.com/theresetuyi/theresetuyi-Capstone-project73rdFIFA-
- [ ] Good job so far @theresetuyi 👏 👏 The link you provided here is not the right one. As the previous reviewer suggested, please deploy your project using the GitHub pages feature provided by GitHub. Here is a good article that will guide you on how to deploy  your website 👉 [Link](https://blog.flycode.com/how-to-deploy-a-static-website-for-free-using-github-pages) Please deploy your site and add the correct link there  😃

2023-02-17 14:42 UTC, BertrandConxy commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] As suggested by the previous reviewer, please add in the  `Acknowledgements` section, credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). This is also considered respectful 😃 👍

2023-02-17 14:42 UTC, BertrandConxy commented on about.html
> +                <div class="intro-message">
- [ ] As suggested by the previous reviewer, please change the color of your heading(Title) to orange like so as to match the design given. Please look at the comparison below 👇 
**Given design**
![image](https://user-images.githubusercontent.com/90222110/219684537-ab43dff5-876e-47e8-b2ed-43799cdf0e61.png)
**Your design**
![image](https://user-images.githubusercontent.com/90222110/219684724-ada63d4e-fc0f-476e-a62a-b9dfd914d2cd.png)

2023-02-17 18:45 UTC, danmainah requested changes
Hi @theresetuyi , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 18:45 UTC, danmainah commented on README.md
> +[Project Link]https://github.com/theresetuyi/theresetuyi-Capstone-project73rdFIFA-
- [ ] @theresetuyi as previously requested kindly deploy your project using GitHub pages, then add the correct link, below is an linkon how to deploy your page using GitHub pages 
-[LINK](https://blog.flycode.com/how-to-deploy-a-static-website-for-free-using-github-pages)

2023-02-17 18:45 UTC, danmainah commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] @theresetuyi  as previously requested kindly add an acknowledgment to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-02-17 18:45 UTC, danmainah commented on index.html
> +                <h1 class="main-title">THE WORLD  FOOTBALL GOVERNING BODY (FIFA)<br> HAS SETTLED ON RWANDA TO HOST THE 73rd FIFA CONGRESS</h1>
- [ ] [optional] It would be nice if you ensured the header color matches the one in the design 
![image](https://user-images.githubusercontent.com/61408860/219757661-ba74ddbf-f71c-47d8-b415-0f82403d188f.png)

2023-02-17 20:31 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @theresetuyi , 


![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


 ## Required Changes ♻️

- [ ] Please deply your project with github pages and include the link in your readme file, as requested by the previous reviewers. Deploying your project is critical because not everyone can run it on their local machine to see how it looks, and even if they can, they won't have the time. Please deploy it so that it is available to everyone.  👌😊
Please check [this article](https://blog.flycode.com/how-to-deploy-a-static-website-for-free-using-github-pages) to see how you can deploy  your project with github pages. 😊

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 22:59 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @theresetuyi , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- Well done deploying the project. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 23:43 UTC, merged